const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom');const root=path.resolve(__dirname,'..'),code='3017620422003';
function app(seed={},setup=()=>{}){const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://ipodbob.github.io/Three-Plates/#pantry',runScripts:'outside-only'}),w=dom.window;w.scrollTo=()=>{};w.confirm=()=>true;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.fetch=async()=>({ok:true,json:async()=>({product:{code,product_name:'Penne pasta',quantity:'500 g'}})});setup(w);for(const [k,v]of Object.entries(seed))w.localStorage.setItem(k,v);for(const f of ['recipes.js','batch-v3.js','core-v3.js','phase1.js','barcode-config.js','pantry-scan.js','app-v3.js'])w.eval(fs.readFileSync(path.join(root,f),'utf8'));const q=s=>w.document.querySelector(s),click=s=>{assert.ok(q(s),s);q(s).click();};return {dom,w,q,click,state:()=>JSON.parse(w.localStorage.getItem('three-plates-v3'))};}
const tick=()=>new Promise(r=>setImmediate(r));
async function lookup(a){a.click('[data-act="pantry-scan"]');a.q('#barcode-number').value=code;a.q('#barcode-number-form').dispatchEvent(new a.w.Event('submit',{bubbles:true,cancelable:true}));await tick();}
test('pantry scan confirms an additive amount, persists match, and prevents repeat submit',async()=>{const a=app();await lookup(a);assert.match(a.q('#scan-result').textContent,/Penne pasta/);a.click('[data-match="pasta"]');a.q('#scan-packs').value=2;a.q('#scan-fraction').value='0.5';const form=a.q('#scan-confirm-form');form.dispatchEvent(new a.w.Event('submit',{bubbles:true,cancelable:true}));form.dispatchEvent(new a.w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(a.state().pantry.find(i=>i.id==='pasta').qty,500);assert.equal(a.state().barcodeMatches[code].qty,500);assert.equal(a.q('#sheet').open,false);a.dom.window.close();});
test('barcode photo uses local decoding and revokes its temporary URL',async()=>{let revoked,decoded;const a=app({},w=>{w.URL.createObjectURL=()=> 'blob:local-test';w.URL.revokeObjectURL=u=>revoked=u;w.ZXingBrowser={BrowserMultiFormatReader:class{async decodeFromImageUrl(url){decoded=url;return {getText:()=>code}}}};});a.click('[data-act="pantry-scan"]');Object.defineProperty(a.q('#scan-photo'),'files',{value:[new a.w.File(['test'],'barcode.jpg',{type:'image/jpeg'})]});a.q('#scan-photo').dispatchEvent(new a.w.Event('change',{bubbles:true}));await tick();assert.equal(decoded,'blob:local-test');assert.equal(revoked,'blob:local-test');assert.match(a.q('#scan-result').textContent,/Penne pasta/);a.dom.window.close();});
test('untrusted product names render as text, and incompatible units require a new amount',async()=>{const a=app({},w=>w.fetch=async()=>({ok:true,json:async()=>({product:{code,product_name:'<img src=x onerror=alert(1)> pasta',quantity:'500 ml'}})}));await lookup(a);assert.equal(a.q('#scan-result img'),null);a.click('[data-match="pasta"]');assert.equal(a.q('#scan-qty').value,'');assert.equal(a.q('#scan-unit').value,'g');a.dom.window.close();});
test('closing during a late camera permission grant releases the acquired track',async()=>{let grant,stopped=0;const a=app({},w=>{Object.defineProperty(w.navigator,'mediaDevices',{value:{getUserMedia:()=>new Promise(r=>grant=r)}});w.ZXingBrowser={BrowserMultiFormatReader:class{async decodeFromStream(){throw Error('should not attach late stream')}}};});a.click('[data-act="pantry-scan"]');a.click('#scan-camera');await tick();a.click('[data-act="close"]');grant({getTracks:()=>[{stop:()=>stopped++}]});await tick();assert.equal(stopped,1);a.dom.window.close();});
test('camera denial keeps photo and number fallbacks available',async()=>{const a=app({},w=>{Object.defineProperty(w.navigator,'mediaDevices',{value:{getUserMedia:async()=>{const e=Error();e.name='NotAllowedError';throw e;}}});w.ZXingBrowser={BrowserMultiFormatReader:class{}};});a.click('[data-act="pantry-scan"]');a.click('#scan-camera');await tick();assert.match(a.q('#scan-status').textContent,/permission was denied/);assert.equal(a.q('#scan-camera').disabled,false);assert.ok(a.q('#scan-photo'));a.dom.window.close();});
test('stale lookup result cannot reopen a dismissed scanner',async()=>{let complete;const a=app({},w=>w.fetch=()=>new Promise(r=>complete=r));a.click('[data-act="pantry-scan"]');a.q('#barcode-number').value=code;a.q('#barcode-number-form').dispatchEvent(new a.w.Event('submit',{bubbles:true,cancelable:true}));a.click('[data-act="close"]');complete({ok:true,json:async()=>({product:{code,product_name:'Pasta'}})});await tick();assert.equal(a.q('#sheet').open,false);assert.equal(a.q('#scan-result').textContent,'');a.dom.window.close();});
