const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..');
test('new equipment buttons persist across reload and return actual specialist recipes',()=>{
 for(const method of ['pressure-cooker','barbecue','microwave']){const a=app();a.click('#f-time-any');a.click('#f-method-'+method);assert.ok(a.q('.meal-card'),method);a.route('batch');a.click('#bf-method-'+method);const b=app({'three-plates-v3':JSON.stringify(a.state())});assert.equal(b.state().filters.method,method);assert.equal(b.q('#f-method-'+method).getAttribute('aria-pressed'),'true');b.route('batch');assert.equal(b.q('#bf-method-'+method).getAttribute('aria-pressed'),'true');a.dom.window.close();b.dom.window.close();}
});
test('specialist search can plan a complete bake and keeps components out of automatic ideas',()=>{
 const a=app();a.click('#f-time-any');for(let i=0;i<5&&a.q('.meal-stepper span').textContent!=='Baking';i++)a.click('#f-meal-next');a.q('#recipe-search').value='almond flour pancakes';a.submit('#search-form');assert.match(a.q('.meal-card').textContent,/King Arthur Baking/);a.click('[data-act="plan-add"]');assert.equal(a.state().plans[0].recipeId,'sp-kingarthur-almond-flour-pancakes-recipe');assert.equal(a.state().plans[0].servings,12);
 a.q('#recipe-search').value='classic puff pastry';a.submit('#search-form');assert.match(a.q('.meal-card').textContent,/Recipe component/);a.q('#recipe-search').value='';a.submit('#search-form');assert.equal(a.w.document.querySelectorAll('.meal-card').length,3);assert.doesNotMatch(a.q('main').textContent,/Recipe component/);a.dom.window.close();
});
test('expanded catalogue can find and plan a full bake with extra time visible',()=>{
 const a=app();a.click('#f-time-any');while(a.q('.meal-stepper span').textContent!=='Baking')a.click('#f-meal-next');a.q('#recipe-search').value='steamed bao';a.submit('#search-form');assert.match(a.q('.meal-card').textContent,/extra time/);assert.match(a.q('.meal-card').textContent,/Hob/);a.click('[data-act="plan-add"]');assert.equal(a.state().plans[0].recipeId,'gf2-steamed-bao-buns');assert.equal(a.state().plans[0].servings,18);a.route('shop');assert.match(a.q('main').textContent,/flour/i);const b=app({'three-plates-v3':JSON.stringify(a.state())});assert.equal(b.state().plans[0].servings,18);a.dom.window.close();b.dom.window.close();
});
test('standalone sides remain searchable but are not offered as a main meal',()=>{
 const a=app();a.click('#f-time-any');a.q('#recipe-search').value='padron peppers';a.submit('#search-form');assert.match(a.q('.meal-card').textContent,/Side dish \/ starter/);a.q('#recipe-search').value='';a.submit('#search-form');assert.equal(a.w.document.querySelectorAll('[data-act="recipe"][data-id="gf2-padron-peppers"]').length,0);assert.equal(a.w.document.querySelectorAll('.meal-card').length,3);a.dom.window.close();
});
test('Dessert and Baking use the shared selector and whole bakes survive reload',()=>{
 const a=app();a.click('#f-time-any');while(a.q('.meal-stepper span').textContent!=='Baking')a.click('#f-meal-next');a.q('#recipe-search').value='no-knead';a.submit('#search-form');assert.match(a.q('.meal-card').textContent,/Full bake · 36/);a.click('[data-act="plan-add"]');assert.equal(a.state().plans[0].servings,36);assert.equal(a.state().plans[0].meal,'Baking');
 const b=app({'three-plates-v3':JSON.stringify(a.state())});assert.equal(b.state().plans[0].servings,36);assert.equal(b.q('.meal-stepper span').textContent,'Baking');b.click('#f-meal-prev');assert.equal(b.q('.meal-stepper span').textContent,'Dessert');b.q('#recipe-search').value='fruit salad';b.submit('#search-form');b.click('[data-act="plan-add"]');assert.equal(b.state().plans.length,2);assert.equal(b.state().plans[1].meal,'Dessert');a.dom.window.close();b.dom.window.close();
});
test('source batch recipes can be planned fresh without entering the batch workflow',()=>{
 const a=app();a.click('#f-time-any');a.q('#recipe-search').value='big-batch';a.submit('#search-form');a.click('[data-act="recipe"][data-id="gf-big-batch-bolognese"]');assert.ok(a.q('.sheet [data-act="plan-add"]'));assert.equal(a.q('.sheet [data-act="batch-add"]'),null);a.click('.sheet [data-act="plan-add"]');assert.equal(a.state().plans[0].recipeId,'gf-big-batch-bolognese');assert.equal(a.state().batches.length,0);a.dom.window.close();
});
test('rated recipe search exposes attribution and plans scalable ingredients',()=>{
 const a=app();a.click('#f-time-any');a.q('#recipe-search').value='air fryer salmon';a.submit('#search-form');assert.ok(a.w.document.querySelectorAll('.meal-card').length>=1);a.click('[data-act="recipe"][data-id="gf-air-fryer-salmon"]');const link=a.q('.sheet a.button');assert.equal(link.href,'https://www.bbcgoodfood.com/recipes/air-fryer-salmon');assert.match(link.textContent,/Read cooking method/);assert.match(a.q('.sheet').textContent,/Source checked 2026-09-28/);a.click('.sheet [data-act="plan-add"]');assert.equal(a.state().plans[0].recipeId,'gf-air-fryer-salmon');a.dom.window.close();
});
test('air fryer filter persists across reload in both cooking modes',()=>{
 const a=app();a.click('#f-method-air-fryer');a.route('batch');a.click('#bf-method-air-fryer');
 const b=app({'three-plates-v3':JSON.stringify(a.state())});assert.equal(b.state().filters.method,'air-fryer');assert.equal(b.q('#f-method-air-fryer').getAttribute('aria-pressed'),'true');b.route('batch');assert.equal(b.state().batchFilters.method,'air-fryer');assert.equal(b.q('#bf-method-air-fryer').getAttribute('aria-pressed'),'true');assert.ok(b.w.document.querySelectorAll('.meal-card').length>=1);a.dom.window.close();b.dom.window.close();
});
test('quantity steppers respect limits, keep focus and update batch portions',()=>{
 const a=app();a.set('#f-servings','12');a.click('#f-servings-plus');assert.equal(a.state().filters.servings,12);a.click('#f-servings-minus');assert.equal(a.state().filters.servings,11);
 a.route('batch');a.set('#bf-days','1');a.set('#bf-people','2');a.click('#bf-days-minus');assert.equal(a.state().batchFilters.days,1);
 a.q('#bf-days-plus').focus();a.click('#bf-days-plus');assert.equal(a.w.document.activeElement.id,'bf-days-plus');assert.equal(a.state().batchFilters.days,2);assert.match(a.q('.portion-summary').textContent,/4 portions/);
 a.set('#bf-days','7');a.click('#bf-days-plus');assert.equal(a.state().batchFilters.days,7);a.set('#bf-people','6');a.click('#bf-people-plus');assert.equal(a.state().batchFilters.people,6);a.set('#bf-people','1');a.click('#bf-people-minus');assert.equal(a.state().batchFilters.people,1);a.dom.window.close();
});
function app(seed={},failStorage=false){
 const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'http://localhost/Three-Plates/',runScripts:'outside-only'}),w=dom.window;
 w.confirm=()=>true;w.scrollTo=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 for(const [key,value] of Object.entries(seed))w.localStorage.setItem(key,value);
 if(failStorage)w.Storage.prototype.setItem=()=>{throw Error('quota');};
 for(const file of ['recipes.js','batch-v3.js','recipes-rated.js','recipes-diverse.js','recipes-expanded.js','recipes-specialists.js','catalogue-review.js','core-v3.js','phase1.js','menus.js','cooking.js','prep.js','cooking-ui.js','barcode-config.js','pantry-scan.js','app-v3.js'])w.eval(fs.readFileSync(path.join(root,file),'utf8'));
 const q=selector=>w.document.querySelector(selector),click=selector=>{assert.ok(q(selector),selector);q(selector).click();if(q("#confirm-action"))q("#confirm-action").click();},set=(selector,value)=>{assert.ok(q(selector),selector);q(selector).value=value;q(selector).dispatchEvent(new w.Event('change',{bubbles:true}));};
 const route=name=>{w.location.hash=name;w.dispatchEvent(new w.HashChangeEvent('hashchange'));};
 const submit=id=>q(id).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 return {w,q,click,set,route,submit,dom,state:()=>JSON.parse(w.localStorage.getItem('three-plates-v3'))};
}
test('a saved meal week previews conflicts, copies new portions and survives reload',()=>{
 const a=app();a.q('#recipe-search').value='Pesto & pea pasta';a.submit('#search-form');a.click('[data-act="plan-add"][data-id="pesto-pea-pasta"]');a.route('plan');a.click('[data-act="menus"]');a.click('[data-act="menu-save"]');a.set('#menu-name','Work lunches');a.submit('#menu-save-form');assert.equal(a.state().menus.length,1);a.click('[data-act="menu-use"]');
 a.set('#menu-new-start',a.state().filters.date);assert.equal(a.q('#menu-apply').disabled,true);const start=a.w.PlatesCore.addDays(a.state().filters.date,7);a.set('#menu-new-start',start);a.q('#menu-adjust').checked=true;a.set('#menu-people','3');assert.match(a.q('#menu-preview').textContent,/3 portions/);a.submit('#menu-use-form');assert.equal(a.state().plans.length,2);assert.equal(a.state().plans[1].servings,3);
 const b=app({'three-plates-v3':JSON.stringify(a.state())});b.route('plan');b.click('[data-act="menus"]');assert.match(b.q('.sheet').textContent,/Work lunches/);b.click('[data-act="menu-delete"]');assert.equal(b.state().menus.length,0);assert.equal(b.state().plans.length,2);a.dom.window.close();b.dom.window.close();
});
test('pantry reminders can be saved, used to find recipes, reloaded and cleared',()=>{
 const a=app();a.route('pantry');a.click('[data-act="pantry-add"]');a.set('#pantry-name','Pasta');a.set('#pantry-qty','500');
 const today=a.w.PlatesCore.today();a.set('#pantry-use-soon',today);a.submit('#pantry-form');
 assert.equal(a.state().pantry[0].useSoon,today);assert.match(a.q('.use-soon-panel').textContent,/Today/);
 const b=app({'three-plates-v3':JSON.stringify(a.state())});b.route('pantry');assert.ok(b.q('.use-soon-panel'));b.click('[data-act="pantry-recipes"]');b.route('choose');assert.equal(b.state().filters.query,'Pasta');assert.ok(b.q('.meal-card'));assert.equal(b.state().pantry[0].qty,500);
 b.route('pantry');b.click('[data-act="pantry-edit"]');b.set('#pantry-use-soon','');b.submit('#pantry-form');assert.equal(b.state().pantry[0].useSoon,undefined);assert.equal(b.q('.use-soon-panel'),null);a.dom.window.close();b.dom.window.close();
});
test('always-stocked pantry entries do not carry dated reminders',()=>{
 const a=app();a.route('pantry');a.click('[data-act="pantry-add"]');a.set('#pantry-name','Pasta');a.set('#pantry-qty','500');a.set('#pantry-use-soon',a.w.PlatesCore.today());a.q('#pantry-always').checked=true;a.submit('#pantry-form');
 assert.equal(a.state().pantry[0].always,true);assert.equal(a.state().pantry[0].useSoon,undefined);assert.equal(a.q('.use-soon-panel'),null);a.dom.window.close();
});
test('refresh keeps locked card and exhausts unseen eligible recipes first',()=>{
 const a=app();const ids=()=>Array.from(a.w.document.querySelectorAll('[data-act="keep"]'),b=>b.dataset.id);
 const first=ids();assert.equal(first.length,3);a.click('[data-act="keep"]');a.click('[data-act="refresh"]');const next=ids();assert.ok(next.includes(first[0]));assert.equal(next.filter(x=>first.slice(1).includes(x)).length,0);a.dom.window.close();
});
test('trip selector preserves usual shop, survives reload, and exact search plans a batch',()=>{
 const a=app();a.route('shop');a.set('#shop-select','Tesco');a.click('#shop-trip');a.set('#shop-select','Aldi');assert.equal(a.state().shop,'Tesco');assert.equal(a.state().tripShop,'Aldi');
 a.route('batch');a.set('#bf-people','2');a.set('#bf-style','variety');a.q('#recipe-search').value='beef bolognese sauce';a.submit('#search-form');assert.equal(a.w.document.querySelectorAll('.meal-card').length,1);a.click('[data-act="batch-add"]');assert.equal(a.q('#batch-portions').value,'6');a.submit('#batch-form');assert.equal(a.state().batches[0].servings,6);
 const restored=app({'three-plates-v3':JSON.stringify(a.state())});restored.route('shop');assert.equal(restored.q('#shop-select').value,'Aldi');restored.click('#shop-trip');assert.equal(restored.q('#shop-select').value,'Tesco');a.dom.window.close();restored.dom.window.close();
});
test('v1 migration preserves original; corrupted current data blocks mutations',()=>{
 const old=JSON.stringify({version:1,pantry:[{id:'rice',qty:750}],bought:{rice:300},prefs:{favourites:['pesto-pea-pasta']}});
 const a=app({'three-plates-v1':old});assert.equal(a.w.localStorage.getItem('three-plates-v1'),old);assert.equal(a.state().pantry[0].qty,750);assert.equal(a.state().bought.rice,300);a.dom.window.close();
 const b=app({'three-plates-v3':'{broken'});b.click('[data-act="plan-add"]');assert.equal(b.w.localStorage.getItem('three-plates-v3'),'{broken');assert.match(b.q('#main').textContent,/saving is paused/);b.dom.window.close();
});
test('storage write failures are visible and keyboard focus survives filter updates',()=>{
 const a=app({},true);a.q('#f-servings').focus();a.set('#f-servings','3');assert.match(a.q('#main').textContent,/cannot save changes/);assert.equal(a.w.document.activeElement.id,'f-servings');a.dom.window.close();
});
test('untrusted custom ingredient names render as text',()=>{
 const a=app({'three-plates-v3':JSON.stringify({version:3,custom:{'custom-x':{name:'<img src=x onerror=alert(1)>',unit:'g'}},pantry:[{id:'custom-x',qty:20}]})});a.route('pantry');assert.equal(a.q('#main img'),null);assert.match(a.q('#main').textContent,/<img/);a.dom.window.close();
});
test('whole batch UI records allocation and prevents a second ingredient deduction',()=>{
 const a=app();a.route('batch');a.q('#recipe-search').value='beef bolognese sauce';a.submit('#search-form');a.click('[data-act="batch-add"]');a.set('#batch-portions','4');a.submit('#batch-form');a.click('[data-act="batch-finish"]');a.set('#freezer-qty','2');a.set('#fridge-qty','2');a.q('#freezer-confirm').checked=true;a.q('#storage-confirm').checked=true;a.submit('#finish-batch-form');assert.equal(a.state().lots.length,2);assert.deepEqual(a.state().batches[0].allocation,{eat:0,fridge:2,freezer:2});a.route('batch');assert.equal(a.q('[data-act="batch-finish"]'),null);a.dom.window.close();
});
test('export and restore use the same validated state including purchase history',async()=>{
 const a=app();a.route('shop');a.set('#shop-select','Aldi');a.route('you');let blob;
 a.w.URL.createObjectURL=b=>{blob=b;return 'blob:test';};a.w.URL.revokeObjectURL=()=>{};a.w.HTMLAnchorElement.prototype.click=()=>{};
 a.click('[data-act="export"]');const text=await new Promise(resolve=>{const r=new a.w.FileReader();r.onload=()=>resolve(r.result);r.readAsText(blob);});
 const b=app();b.route('you');await new Promise(r=>setImmediate(r));Object.defineProperty(b.q('#backup-file'),'files',{value:[{size:text.length,text:async()=>text}]});b.q('#backup-file').dispatchEvent(new b.w.Event('change',{bubbles:true}));await new Promise(r=>setImmediate(r));b.click('#confirm-action');assert.equal(b.state().shop,'Aldi');assert.deepEqual(b.state(),JSON.parse(text));a.dom.window.close();b.dom.window.close();
});
test('invalid restore and cross-tab update cannot overwrite existing browser data',async()=>{
 const a=app();a.route('shop');a.set('#shop-select','Tesco');const prior=a.w.localStorage.getItem('three-plates-v3');a.route('you');
 Object.defineProperty(a.q('#backup-file'),'files',{value:[{size:12,text:async()=>'{not json'}]});a.q('#backup-file').dispatchEvent(new a.w.Event('change',{bubbles:true}));await new Promise(r=>setImmediate(r));assert.equal(a.w.localStorage.getItem('three-plates-v3'),prior);
 a.w.dispatchEvent(new a.w.StorageEvent('storage',{key:'three-plates-v3',newValue:prior}));a.route('shop');a.set('#shop-select','Aldi');assert.equal(a.w.localStorage.getItem('three-plates-v3'),prior);assert.match(a.q('#main').textContent,/another tab/);a.dom.window.close();
});
test('shopping UI records actual whole packs and keeps them through a trip change',()=>{
 const a=app();a.route('batch');a.q('#recipe-search').value='chilli';a.submit('#search-form');a.click('[data-act="batch-add"]');a.set('#batch-portions','6');a.submit('#batch-form');a.route('shop');a.set('#pack-mode','packs');a.click('[data-act="bought"][data-id="beef-mince"]');assert.equal(a.state().bought['beef-mince'],1000);assert.equal(a.state().purchaseHistory[0].pack.size,500);a.click('#shop-trip');a.set('#shop-select','Tesco');assert.equal(a.state().purchaseHistory[0].retailer,'none');a.click('[data-act="stock-bought"]');assert.equal(a.state().pantry.find(p=>p.id==='beef-mince').qty,1000);a.dom.window.close();
});
test('shared Choose screen exposes inline batch settings and keeps each workflow intact',()=>{
 const a=app();assert.equal(a.w.document.querySelectorAll('#nav a').length,4);assert.equal(a.q('#batch-mode').checked,false);assert.equal(a.q('#batch-options').hidden,true);
 a.set('#f-servings','3');a.click('#batch-mode');assert.equal(a.q('#batch-mode').checked,true);assert.equal(a.q('#batch-options').hidden,false);assert.ok(a.q('#bf-days'));assert.equal(a.q('h1').textContent,'What’s cooking?');assert.equal(a.q('#nav [aria-current="page"]').getAttribute('href'),'#choose');
 a.set('#bf-people','2');a.click('[data-act="mode"][data-id="pantry"]');assert.equal(a.state().batchFilters.mode,'pantry');assert.equal(a.state().filters.mode,'any');
 a.click('#batch-mode');assert.equal(a.q('#f-servings').value,'3');a.click('#batch-mode');assert.equal(a.q('#bf-people').value,'2');assert.equal(a.w.document.querySelectorAll('.meal-card').length,3);a.dom.window.close();
});
test('visible time and method buttons filter both workflows and retain keyboard focus',()=>{
 const a=app();assert.equal(a.q('.tap-filters select'),null);assert.equal(a.q('.tap-filters details'),null);
 a.q('#f-time-any').focus();a.click('#f-time-any');assert.equal(a.state().filters.time,'any');assert.equal(a.w.document.activeElement.id,'f-time-any');
 a.click('#f-method-hob');assert.equal(a.state().filters.method,'hob');assert.equal(a.q('#f-method-hob').getAttribute('aria-pressed'),'true');
 a.click('#batch-mode');a.click('#bf-time-30');a.click('#bf-method-hob');assert.equal(a.state().batchFilters.time,'30');assert.equal(a.state().batchFilters.method,'hob');assert.equal(a.state().filters.time,'any');a.dom.window.close();
});
test('pantry search filters names without modifying stock and clears cleanly',()=>{const a=app({'three-plates-v3':JSON.stringify({version:3,pantry:[{id:'rice',qty:400},{id:'pasta',qty:200}]})});a.route('pantry');a.q('#pantry-search').value='rice';a.submit('#pantry-search-form');assert.equal(a.w.document.querySelectorAll('.pantry-item').length,1);assert.match(a.q('.pantry-item').textContent,/rice/i);a.q('#pantry-search').value='no such product';a.submit('#pantry-search-form');assert.match(a.q('main').textContent,/No pantry items match/);a.click('[data-act="pantry-search-clear"]');assert.equal(a.w.document.querySelectorAll('.pantry-item').length,2);a.dom.window.close();});
test('searchable food preferences accept an ingredient name and reject unknown text',()=>{const a=app();a.route('you');a.q('#pref-exclusions').value='pasta';a.submit('.pref-form[data-key="exclusions"]');assert.ok(a.state().prefs.exclusions.includes('pasta'));a.q('#pref-exclusions').value='not a real ingredient';a.submit('.pref-form[data-key="exclusions"]');assert.equal(a.state().prefs.exclusions.length,1);a.dom.window.close();});
test('failed plan writes roll back and do not report a saved meal',()=>{const a=app({},true);a.click('[data-act="plan-add"]');assert.match(a.q('#main').textContent,/cannot save changes/);assert.doesNotMatch(a.q('#toast').textContent,/added to/i);a.route('plan');assert.equal(a.w.document.querySelectorAll('.plan-card').length,0);a.dom.window.close();});
test('cuisines are searchable and only selected choices occupy the settings page',()=>{const a=app();a.route('you');assert.equal(a.w.document.querySelectorAll('[data-act="cuisine"]').length,0);a.q('#pref-cuisine').value='Italian';a.submit('#cuisine-form');assert.ok(a.state().prefs.cuisines.includes('Italian'));assert.equal(a.w.document.querySelectorAll('[data-act="cuisine"]').length,1);a.click('[data-act="cuisine"]');assert.equal(a.state().prefs.cuisines.length,0);a.dom.window.close();});
test('linking custom pantry stock into a recipe ingredient combines rather than replaces',()=>{const a=app({'three-plates-v3':JSON.stringify({version:3,custom:{'custom-penne':{id:'custom-penne',name:'Brand penne',unit:'g',group:'Other'}},pantry:[{id:'custom-penne',qty:250},{id:'pasta',qty:100}]})});a.route('pantry');a.click('[data-act="pantry-link"]');a.q('#link-target').value='pasta';a.q('#link-target').dispatchEvent(new a.w.Event('change'));assert.equal(a.q('#link-qty').value,'250');a.q('#link-confirm').checked=true;a.submit('#pantry-link-form');assert.equal(a.state().pantry.length,1);assert.equal(a.state().pantry[0].qty,350);assert.equal(a.state().pantry[0].id,'pasta');a.dom.window.close();});
test('ordinary pantry editing cannot silently overwrite a different ingredient',()=>{const a=app({'three-plates-v3':JSON.stringify({version:3,custom:{'custom-penne':{id:'custom-penne',name:'Brand penne',unit:'g',group:'Other'}},pantry:[{id:'custom-penne',qty:250},{id:'pasta',qty:100}]})});a.route('pantry');a.click('[data-act="pantry-edit"][data-id="custom-penne"]');a.q('#pantry-name').value='pasta';a.submit('#pantry-form');assert.equal(a.state().pantry.length,2);assert.equal(a.state().pantry.find(p=>p.id==='pasta').qty,100);assert.match(a.q('#toast').textContent,/Link to recipes/);a.dom.window.close();});
test('fresh meal flows through partial pantry, pack shopping, transfer and one cooking deduction',()=>{const a=app({'three-plates-v3':JSON.stringify({version:3,pantry:[{id:'pasta',qty:100}],packMode:'packs',packs:{none:{pasta:{size:500}}}})});a.q('#recipe-search').value='Pesto & pea pasta';a.submit('#search-form');a.click('[data-act="plan-add"][data-id="pesto-pea-pasta"]');a.route('shop');a.click('[data-act="bought"][data-id="pasta"]');assert.equal(a.state().bought.pasta,500);for(const b of [...a.w.document.querySelectorAll('[data-act="bought"]')]){if(b.dataset.id!=='pasta')a.click('[data-act="bought"][data-id="'+b.dataset.id+'"]');}a.click('[data-act="stock-bought"]');assert.equal(a.state().pantry.find(p=>p.id==='pasta').qty,600);assert.equal(Object.keys(a.state().bought).length,0);a.route('plan');a.click('[data-act="plan-finish"]');assert.equal(a.state().pantry.find(p=>p.id==='pasta').qty,420);assert.equal(a.state().plans[0].cooked,true);assert.equal(a.q('[data-act="plan-finish"]'),null);a.route('shop');assert.equal(a.w.document.querySelectorAll('[data-act="bought"]').length,0);const b=app({'three-plates-v3':JSON.stringify(a.state())});assert.equal(b.state().pantry.find(p=>p.id==='pasta').qty,420);assert.equal(b.state().plans[0].cooked,true);a.dom.window.close();b.dom.window.close();});
test('destructive actions use cancellable in-app confirmation and submit only once',()=>{const a=app({'three-plates-v3':JSON.stringify({version:3,pantry:[{id:'pasta',qty:200}]})});a.route('pantry');a.q('[data-act="pantry-remove"]').click();assert.ok(a.q('#confirm-action'));assert.equal(a.state().pantry.length,1);a.q('[data-act="close"]').click();assert.equal(a.state().pantry.length,1);a.q('[data-act="pantry-remove"]').click();const confirm=a.q('#confirm-action');confirm.click();confirm.click();assert.equal(a.state().pantry.length,0);a.dom.window.close();});
test('plan portion editing uses the shared stepper and updates shopping requirements',()=>{const a=app();a.q('#recipe-search').value='Pesto & pea pasta';a.submit('#search-form');a.click('[data-act="plan-add"][data-id="pesto-pea-pasta"]');a.route('plan');a.click('[data-act="plan-edit"]');assert.equal(a.q('#plan-portions').value,'2');a.click('#plan-portions-plus');a.submit('#plan-portions-form');assert.equal(a.state().plans[0].servings,3);a.route('shop');assert.match(a.q('[data-act="bought"][data-id="pasta"]').closest('.shopping-row').textContent,/270/);a.dom.window.close();});
test('replacement confirmation preserves the meal until explicitly confirmed',()=>{const a=app();a.q('#recipe-search').value='Pesto & pea pasta';a.submit('#search-form');a.click('[data-act="plan-add"][data-id="pesto-pea-pasta"]');const before=JSON.stringify(a.state().plans);a.q('[data-act="plan-add"][data-id="pesto-pea-pasta"]').click();assert.ok(a.q('#confirm-action'));a.q('[data-act="close"]').click();assert.equal(JSON.stringify(a.state().plans),before);a.q('[data-act="plan-add"][data-id="pesto-pea-pasta"]').click();a.q('#confirm-action').click();assert.equal(a.state().plans.length,1);a.dom.window.close();});
test('restore confirmation refuses to overwrite data changed while reviewing the backup',async()=>{const a=app();a.route('shop');a.set('#shop-select','Tesco');a.route('you');await new Promise(r=>setImmediate(r));const backup=JSON.stringify({...a.state(),shop:'Aldi'});Object.defineProperty(a.q('#backup-file'),'files',{value:[{size:backup.length,text:async()=>backup}]});a.q('#backup-file').dispatchEvent(new a.w.Event('change',{bubbles:true}));await new Promise(r=>setImmediate(r));assert.ok(a.q('#confirm-action'));const updated=JSON.stringify({...a.state(),shop:'Waitrose'});a.w.localStorage.setItem('three-plates-v3',updated);a.q('#confirm-action').click();assert.equal(a.w.localStorage.getItem('three-plates-v3'),updated);assert.match(a.q('#toast').textContent,/Data changed/);a.dom.window.close();});
test('failed reset restores already-removed current data and leaves old backup intact',()=>{const a=app();a.route('shop');a.set('#shop-select','Tesco');a.w.localStorage.setItem('three-plates-v1','legacy-backup');const prior=a.w.localStorage.getItem('three-plates-v3'),remove=a.w.Storage.prototype.removeItem;a.w.Storage.prototype.removeItem=function(key){if(key==='three-plates-v1')throw Error('blocked');return remove.call(this,key)};a.route('you');a.click('[data-act="reset"]');assert.equal(a.w.localStorage.getItem('three-plates-v3'),prior);assert.equal(a.w.localStorage.getItem('three-plates-v1'),'legacy-backup');assert.match(a.q('#toast').textContent,/Existing data was retained/);a.dom.window.close();});
test('copied shopping list names the active trip shop rather than usual shop',async()=>{const a=app();a.route('shop');await new Promise(r=>setImmediate(r));a.set('#shop-select','Aldi');a.click('#shop-trip');a.set('#shop-select','Tesco');a.click('[data-act="copy-list"]');await new Promise(r=>setImmediate(r));assert.match(a.q('#copy-text').value,/THREE PLATES — Tesco/);assert.equal(a.state().shop,'Aldi');a.dom.window.close();});

test('planned recipe views use their own servings and cannot accidentally add another meal',()=>{
 const a=app();a.set('#f-servings','4');a.q('#recipe-search').value='Pesto & pea pasta';a.submit('#search-form');a.click('[data-act="plan-add"][data-id="pesto-pea-pasta"]');a.set('#f-servings','1');a.route('plan');
 a.click('[data-act="recipe"][data-context="plan"]');assert.match(a.q('#recipe-amounts').textContent,/360 g/);assert.match(a.q('.sheet .notice').textContent,/4 portions/);assert.equal(a.q('.sheet [data-act="plan-add"]'),null);assert.equal(a.q('#recipe-portions'),null);a.click('[data-act="close"]');
 a.route('batch');a.q('#recipe-search').value='beef bolognese sauce';a.submit('#search-form');a.click('[data-act="batch-add"]');a.set('#batch-portions','6');a.submit('#batch-form');a.route('plan');a.click('[data-act="recipe"][data-context="batch"]');assert.match(a.q('.sheet .notice').textContent,/6 portions/);assert.match(a.q('#recipe-amounts').textContent,/750 g/);assert.equal(a.q('.sheet [data-act="batch-add"]'),null);a.dom.window.close();
});
test('stored meal recipe separates its fresh side from already-cooked ingredients',()=>{
 const setup=app(),C=setup.w.PlatesCore,R=setup.w.PLATES_DATA.recipes,s=C.defaults(),now=Date.now();
 s.batches.push({id:'batch-test',recipeId:'prep-chilli',servings:6,date:C.today(),cooked:false});C.finishBatch(s,'batch-test',{eat:0,fridge:0,freezer:6,cookedAt:new Date(now-60000).toISOString(),freezerConfirmed:true},R,now);
 C.scheduleLot(s,s.lots[0].id,C.today(),'Dinner',2,1,'rice',R,now,'18:00');
 const a=app({'three-plates-v3':JSON.stringify(s)});a.route('plan');a.click('[data-act="recipe"][data-context="plan"]');assert.match(a.q('.sheet').textContent,/Fresh side for this meal/);assert.match(a.q('.sheet').textContent,/150 g/);assert.match(a.q('.sheet').textContent,/Already prepared ingredients/);assert.match(a.q('#recipe-amounts').textContent,/250 g/);a.click('[data-act="close"]');
 a.route('pantry');a.click('[data-act="pantry-tab"][data-id="prepared"]');a.click('[data-act="recipe"][data-context="lot"]');assert.match(a.q('.sheet .notice').textContent,/Original cooked batch.*6 portions/);assert.match(a.q('#recipe-amounts').textContent,/750 g/);assert.equal(a.state().lots[0].portions,6);setup.dom.window.close();a.dom.window.close();
});

test('broad recipe searches progressively reveal unique results and reset on filter changes',()=>{
 const a=app();a.click('#f-time-any');a.q('#recipe-search').value='chicken';a.submit('#search-form');const cards=()=>Array.from(a.w.document.querySelectorAll('.meal-card'));const ids=()=>cards().map(c=>c.querySelector('[data-act="recipe"]').dataset.id);assert.equal(cards().length,12);const first=ids();a.click('#search-more');assert.equal(cards().length,24);assert.deepEqual(ids().slice(0,12),first);assert.equal(new Set(ids()).size,24);assert.equal(a.w.document.activeElement.id,'recipe-title-'+ids()[12]);
 let clicks=0;while(a.q('#search-more')&&clicks++<100)a.click('#search-more');assert.equal(a.q('#search-more'),null);assert.match(a.q('.search-progress').textContent,new RegExp('Showing '+cards().length+' of '+cards().length));assert.equal(new Set(ids()).size,cards().length);
 a.q('#recipe-search').value='pasta';a.submit('#search-form');assert.equal(cards().length,12);a.click('#search-more');a.click('#f-method-hob');assert.ok(cards().length<=12);a.click('[data-act="clear-search"]');assert.equal(cards().length,3);assert.equal(a.q('#search-more'),null);a.dom.window.close();
});

test('reviewed sides stay searchable without occupying automatic dinner choices',()=>{
 const a=app();a.click('#f-time-any');a.click('#f-method-air-fryer');a.q('#recipe-search').value='radishes';a.submit('#search-form');assert.match(a.q('.meal-card').textContent,/Side dish/);assert.equal(a.q('[data-act="recipe"]').dataset.id,'sp-skinnytaste-air-fryer-radishes');a.click('[data-act="clear-search"]');for(let i=0;i<12;i++){assert.doesNotMatch(a.q('main').textContent,/Air Fryer Radishes/);a.click('[data-act="refresh"]');}
 a.click('#f-method-microwave');a.q('#recipe-search').value='macaroni';a.submit('#search-form');assert.match(a.q('.meal-card').textContent,/Microwave macaroni cheese/);a.dom.window.close();
});

test('recipe side picker previews amounts, saves to the meal and shopping, and survives reload',()=>{
 const a=app();a.q('#recipe-search').value='Pesto & pea pasta';a.submit('#search-form');a.click('[data-act="plan-add"][data-id="pesto-pea-pasta"]');a.route('plan');a.click('[data-act="plan-side"]');assert.equal(a.w.document.querySelectorAll('.side-option').length,8);a.click('#side-more');assert.equal(a.w.document.querySelectorAll('.side-option').length,16);
 a.q('#side-search').value='radishes';a.q('#side-search').dispatchEvent(new a.w.Event('input',{bubbles:true}));assert.equal(a.w.document.querySelectorAll('.side-option').length,1);assert.match(a.q('#side-results').textContent,/Ingredients for 2 portions/);assert.match(a.q('#side-results').textContent,/Skinnytaste/);const stock=JSON.stringify(a.state().pantry);a.click('[data-act="side-choice"][data-id="recipe:sp-skinnytaste-air-fryer-radishes"]');assert.equal(a.state().plans[0].side,'recipe:sp-skinnytaste-air-fryer-radishes');assert.equal(JSON.stringify(a.state().pantry),stock);
 const b=app({'three-plates-v3':JSON.stringify(a.state())});b.route('plan');assert.match(b.q('main').textContent,/Air Fryer Radishes added separately/);b.click('[data-context="plan"]');assert.match(b.q('.sheet').textContent,/Fresh side.*Air Fryer Radishes/);assert.ok(b.q('.sheet a[href="https://www.skinnytaste.com/air-fryer-radishes/"]'));b.click('.sheet [data-act="close"]');b.route('shop');assert.match(b.q('main').textContent,/radishes/i);b.route('plan');b.click('[data-act="plan-side"]');b.click('[data-act="side-choice"][data-id="none"]');assert.equal(b.state().plans[0].side,'none');a.dom.window.close();b.dom.window.close();
});

test('side save failure keeps the original plan and the picker open',()=>{
 const a=app();a.q('#recipe-search').value='Pesto & pea pasta';a.submit('#search-form');a.click('[data-act="plan-add"][data-id="pesto-pea-pasta"]');const saved=JSON.stringify(a.state());a.dom.window.close();const b=app({'three-plates-v3':saved},true);b.route('plan');b.click('[data-act="plan-side"]');b.click('[data-act="side-choice"][data-id="rice"]');assert.equal(b.state().plans[0].side,'none');assert.ok(b.q('#sheet').open);assert.match(b.q('#toast').textContent,/cannot save/);b.dom.window.close();
});

test('recipe and allocation touch steppers update quantities and re-enable correctly at limits',()=>{
 const a=app();a.q('#recipe-search').value='Pesto & pea pasta';a.submit('#search-form');a.click('[data-act="recipe"][data-id="pesto-pea-pasta"]');a.click('#recipe-portions-minus');assert.equal(a.q('#recipe-portions').value,'1');assert.equal(a.q('#recipe-portions-minus').getAttribute('aria-disabled'),'true');a.click('#recipe-portions-plus');assert.equal(a.q('#recipe-portions-minus').getAttribute('aria-disabled'),'false');a.click('#recipe-portions-plus');assert.match(a.q('#recipe-amounts').textContent,/270 g/);a.click('.sheet [data-act="plan-add"]');assert.equal(a.state().plans[0].servings,3);
 a.route('batch');a.click('#bf-time-any');a.click('[data-act="batch-add"]');a.set('#batch-portions','4');a.submit('#batch-form');a.route('plan');a.click('[data-act="batch-finish"]');a.click('#freezer-qty-minus');a.click('#eat-now-plus');assert.equal(a.q('#freezer-qty').value,'3');assert.equal(a.q('#eat-now').value,'1');assert.equal(a.q('#eat-now-minus').getAttribute('aria-disabled'),'false');a.q('#freezer-confirm').checked=true;a.q('#storage-confirm').checked=true;a.submit('#finish-batch-form');a.route('pantry');a.click('[data-act="lot-plan"]');a.set('#lot-days','3');a.set('#lot-servings','2');assert.equal(a.q('#lot-days').value,'1');assert.equal(a.q('#lot-days-plus').getAttribute('aria-disabled'),'true');a.dom.window.close();
});
